import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import { Toaster } from "sonner"; // <--- 1. IMPORTANTE: Importalo acá

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clipp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Theme> 
            {children} 
        </Theme>

        {/* 2. IMPORTANTE: Ponelo acá al final, antes de cerrar el body */}
        {/* Le agregamos zIndex alto para que aparezca POR ENCIMA de los modales */}
        <Toaster 
            position="bottom-right" 
            richColors 
            style={{ zIndex: 99999, position: 'fixed' }} 
        />
      </body> 
    </html>
  );
}